# Python curriculum : week 17 day 5

2019-04-26 SSAFY

* JS

  : Promise, async function
  
## I. Promise

> [`Promise`](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise)는 비동기 조작의 최종 완료나 실패를 표현해주는 객체입니다. 

### Promise method

* `.then()`

  : 성공시 결과를 넘겨준다.

  * then 의 반환값은 `Promise` 객체이다.

    따라서 depth가 깊은 콜백 함수, callback hell을 then chaining 을 통해 대체할 수 있다.

    ```js
    Promise
        .then()
    	.then()
    	.then()
    	.then()
    	.then()
    ```

* `.catch()`

  : 실패시 결과를 넘겨준다.

* example

  ```js
  const orderCoffee = (order) => new Promise((resolve, reject) => {
      // 비동기적인 작업
      if (order === undefined) {
          // 실패했을 때
          reject('손님 주문 안하셨는데요;');
      } else {
          let coffee;
          setTimeout(() => {
              coffee = order;
              resolve(coffee);
          }, 1000);
      }
  });
  
  orderCoffee('아아')
      .then(coffee => {
          console.log(`주문하신 ${coffee} 나왔습니다.`);
          return orderCoffee('라떼')
      })
      .then(coffee => console.log(`주문하신 ${coffee} 나왔습니다.`))
      .catch(error => console.log(error));
  ```



## II. Async Function

* async function

  : 비동기적인 로직을 포함하는 함수

  * 정의 할 때에 앞에 async 키워드를 붙여준다.
  * 실제로 비동기적 함수 앞에는 await 키워드를 붙여서 그 함수가 모두 실행될 때까지 기다리게 한다.
  * `Promise` 의 `catch()` 와 같은 error-handling은 try catch 구문을 통해 할 수 있다.

  * example

    ```js
    // 위에서 정의한 orderCoffee promise 참고
    
    const getCoffee = async (order) => {
        try {
            const coffee = await orderCoffee(order);
            console.log(`주문하신 ${coffee} 나왔습니다.`);
        } catch (error) {
            console.log(error)  
        };
    }
    
    getCoffee('따아'); // output : 주문하신 따아 나왔습니다.
    ```

    * 위의 예에서도 `getCoffee` async function 도 `Promise` 객체를 반환한다.